name: Deploy to Google Cloud Storage

on:
  # trigger action manually
  workflow_dispatch:
    inputs:
      deploy_to_main_path:
        description: 'Deploy for production (DANGER)'
        required: true
        default: false
        type: boolean

jobs:
  deploy:
    # only run deploy action in copies of the template repo
    if: ${{ github.repository != 'rbb-data/svelte-starter' }}
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Create .env.local file
        run: |
          touch .env.local
          echo GOOGLE_CONNECT_KEY=$GOOGLE_CONNECT_KEY >> .env.local
        env:
          GOOGLE_CONNECT_KEY: ${{ secrets.GOOGLE_CONNECT_KEY }}

      - name: Install
        run: npm ci

      - name: Update data
        run: npm run update:all

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GC_STORAGE_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Deploy to main page
        run: npm run deploy
        if: ${{ github.event.inputs.deploy_to_main_path == 'true' }}

      - name: Deploy to experimental page
        run: npm run deploy--experimental
        if: ${{ github.event.inputs.deploy_to_main_path == 'false' }}

      - name: Import environment variables
        run: cat .env >> $GITHUB_ENV

      - name: Add job summary
        run: echo Deployed to https://storage.googleapis.com/rbb-data-static${BASE_PATH}${SUFFIX}/index.html >> $GITHUB_STEP_SUMMARY
        env:
          BASE_PATH: ${{ env.BASE_PATH }}
          SUFFIX: "${{ github.event.inputs.deploy_to_main_path == 'false' && '-experimental' || '' }}"
