name: Deploy Histoire docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    # only run deploy action in the template repo itself
    if: ${{ github.repository == 'rbb-data/svelte-starter' }}
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Build docs
        run: npm run docs:build

      - name: Deploy to GitHub pages
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: .histoire/dist
