name: Setup templated project

on:
  push:
    branches:
      - main

jobs:
  setup:
    # only run deploy action on first commit in copies of the template repo
    if: ${{ github.repository != 'rbb-data/svelte-starter' && github.event.head_commit.message == 'Initial commit' }}
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Setup repo
        run: |
          [ -d docs ] && rm -rf docs/
          sed -i 's/{project-name}/'"$(basename $(pwd))"'/g' package.json .env iframe.html

      - name: Commit and push
        run: |-
          git diff
          git config --global user.email "setup-bot@example.com"
          git config --global user.name "setup-bot"
          git diff --quiet || (git add --all && git commit -m "setup")
          git push
