name: Setup templated project

on:
  push:
    branches:
      - main

jobs:
  setup:
    # only run setup action on first commit in copies of the template repo
    if: ${{ github.repository != 'rbb-data/svelte-starter' && github.event.head_commit.message == 'Initial commit' }}
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Setup repo
        run: |
          rm -rf .storybook/
          rm -f .github/workflows/storybook.yml
          node scripts/remove-storybook.js
          node scripts/update-readme.js

          sed -i 's/{project-name}/'"$(basename $(pwd))"'/g' package.json .env iframe.html README.md
          sed -i '1s/.*/# '"$(basename $(pwd))"'/' README.md

      - name: Commit and push
        run: |-
          git diff
          git config --global user.email "setup-bot@example.com"
          git config --global user.name "setup-bot"
          git diff --quiet || (git add --all && git commit -m "setup")
          git push
