name: Deploy storybook

on:
  push:
    branches:
      - main

jobs:
  deploy:
    # only run deploy action in the template repo itself
    if: ${{ github.repository == 'rbb-data/svelte-starter' }}
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install
        run: npm ci

      # this is necessary to ensure .svelte-kit/dev/ exists
      - name: Spin up dev server
        run: ( npm run dev ) & sleep 60 ; kill $!

      - name: Deploy storybook
        run: npm run storybook:deploy -- --ci
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
