name: Deploy storybook

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    # only run deploy action in the template repo itself
    if: ${{ github.repository == 'rbb-data/svelte-starter' }}
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Install
        run: npm ci

      # this is necessary to ensure .svelte-kit/runtime exists
      - name: Spin up dev server
        run: ( npm run dev ) & sleep 30 ; kill $!

      - name: Build
        run: npm run storybook:build

      - name: Deploy storybook
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: docs-build
